/* Generated By:JJTree: Do not edit this line. ASTAdd.java */

package RTi.DataTest.ExpressionParser;

public class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(DataTestExpressionParser p, int id) {
    super(p, id);
  }

}
