/* Generated By:JJTree: Do not edit this line. ASTDouble.java */

package RTi.DataTest.ExpressionParser;

public class ASTDouble extends SimpleNode {
  public ASTDouble(int id) {
    super(id);
  }

  public ASTDouble(DataTestExpressionParser p, int id) {
    super(p, id);
  }

private double __value = -999.0;

public double getValue() {
	return __value;
}

public void setValue(double value) {
	__value = value;
}

}
