/* Generated By:JJTree: Do not edit this line. ASTFunction.java */

package RTi.DataTest.ExpressionParser;

import java.util.Vector;

public class ASTFunction extends SimpleNode {
  public ASTFunction(int id) {
    super(id);
  }

  public ASTFunction(DataTestExpressionParser p, int id) {
    super(p, id);
  }

private String __name = null;

private Vector __params = new Vector();

public String getName() {
	return __name;
}

public void setName(String name) {
	__name = name;
}

public void addParam(String s) {
	__params.add(s);
}

public Vector getParams() {
	return __params;
}

}
