/* Generated By:JJTree: Do not edit this line. ASTInteger.java */

package RTi.DataTest.ExpressionParser;

public class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(DataTestExpressionParser p, int id) {
    super(p, id);
  }

private int __value = -999;

public int getValue() {
	return __value;
}

public void setValue(int value) {
	__value = value;
}

}
