/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */

package RTi.DataTest.ExpressionParser;

public class ASTIdentifier extends SimpleNode {
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(DataTestExpressionParser p, int id) {
    super(p, id);
  }

private String __name = null;

public String getName() {
	return __name;
}

public void setName(String name) {
	__name = name;
}

}
