/* Generated By:JJTree: Do not edit this line. ASTLogical.java */

package RTi.DataTest.ExpressionParser;

public class ASTLogical extends SimpleNode {
  public ASTLogical(int id) {
    super(id);
  }

  public ASTLogical(DataTestExpressionParser p, int id) {
    super(p, id);
  }

}
