/* Generated By:JJTree: Do not edit this line. ASTNegative.java */

package RTi.DataTest.ExpressionParser;

public class ASTNegative extends SimpleNode {
  public ASTNegative(int id) {
    super(id);
  }

  public ASTNegative(DataTestExpressionParser p, int id) {
    super(p, id);
  }

}
