/* Generated By:JJTree: Do not edit this line. ASTStart.java */

package RTi.DataTest.ExpressionParser;

public class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(DataTestExpressionParser p, int id) {
    super(p, id);
  }

}
