/* Generated By:JJTree: Do not edit this line. ASTTSIdentifier.java */

package RTi.DataTest.ExpressionParser;

public class ASTTSIdentifier extends SimpleNode {
  public ASTTSIdentifier(int id) {
    super(id);
  }

  public ASTTSIdentifier(DataTestExpressionParser p, int id) {
    super(p, id);
  }

private String __name = null;

public String getName() {
	return __name;
}

public void setName(String name) {
	__name = name;
}

}
