/* Generated By:JJTree: Do not edit this line. I:\develop\DataTest\libDataTestJava\src\RTi\DataTest\ExpressionParser\DataTestExpressionParserTreeConstants.java */

package RTi.DataTest.ExpressionParser;

public interface DataTestExpressionParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTLOGICAL = 2;
  public int JJTCOMP = 3;
  public int JJTADD = 4;
  public int JJTMULT = 5;
  public int JJTNEGATIVE = 6;
  public int JJTFUNCTION = 7;
  public int JJTIDENTIFIER = 8;
  public int JJTINTEGER = 9;
  public int JJTDOUBLE = 10;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Logical",
    "Comp",
    "Add",
    "Mult",
    "Negative",
    "Function",
    "Identifier",
    "Integer",
    "Double",
  };
}
