/* Generated By:JJTree&JavaCC: Do not edit this line. DataTestExpressionParserConstants.java */
package RTi.DataTest.ExpressionParser;

public interface DataTestExpressionParserConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 6;
  int DOUBLE_LITERAL = 7;
  int DOUBLE_LITERAL1 = 8;
  int DOUBLE_LITERAL2 = 9;
  int DECIMAL_LITERAL = 10;
  int HEX_LITERAL = 11;
  int OCTAL_LITERAL = 12;
  int IDENTIFIER = 13;
  int LETTER = 14;
  int DIGIT = 15;
  int STAR = 16;
  int DOT = 17;
  int TSID = 18;
  int QUOTED_STRING = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<token of kind 4>",
    "<token of kind 5>",
    "<INTEGER_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<DOUBLE_LITERAL1>",
    "<DOUBLE_LITERAL2>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<STAR>",
    "<DOT>",
    "<TSID>",
    "<QUOTED_STRING>",
    "\"\\n\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
