package RTi.Util.IO;

/**
This interface defines the implementation to provide command processor events.  Because
the implementation must provide a way to register listeners for the events, the only
method to add listeners.
*/
public interface CommandProcessorEventProvider {
	
	/**
	 * Add a listener to receive the events generated by the implementation.
	 * @param listener the listener to receive the events.
	 */
	public void addCommandProcessorEventListener ( CommandProcessorEventListener listener );
}
