package RTi.Util.IO;

import java.io.File;
import java.util.List;

/**
 * This interface defines behavior for classes that generate output files.
 * For example, it is intended to provide a generic way for calling code to
 * get a list of any files created by a component.
 * @author sam
 *
 */
public interface FileGenerator {

	/**
	 * Return the list of File instances for output files.  The main intent is to get
	 * a list of files, not return open files, etc.
	 * @return the list of files generated by a component.  Absolute path references
	 * should be returned and can be abbreviated by calling code.
	 */
	public List<File> getGeneratedFileList ();
}